name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy built file to root
        run: cp dist/simple-weather-card-bundle.js simple-weather-card-bundle.js

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            simple-weather-card-bundle.js
            info.md
            hacs.json
            README.md
            CHANGELOG.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
